name: Bug Report
description: File a bug report
title: "Connector Configuration Guide"
labels: ["f"]
body:
  - type: textarea
    id: Requirement
    attributes:
      label: Requirement
      value: 'xxxxxxxxxxxxx'
    validations:
      required: true
  - type: textarea
    id: Data-Source-Installation
    attributes:
      label: Data Source Installation
      value: 'xxxxxxxxxxxxxxxx'
    validations:
      required: true
  - type: textarea
    id: Known-Issues
    attributes:
      label: Data Source Installation
      value: 'xxxxxxxxxxxxxxxx'
    validations:
      required: true
  - type: checkboxes
    id: feature-as-source
    attributes:
      label: 插件实现的源功能 Implemented Features - as Source
      options:
        - label: 全量读 source-feature-full-sync
          required: true
        - label: 增量读 source-feature-cdc
        - label: 全量总数统计 source-feature-count
        - label: 增量指定时间 source-feature-cdc-time-point
        - label: 高级查询 source-feature-advance-query
        - label: 查询索引 source-feature-load-index
        - label: 加载模型 source-feature-load-schema
        - label: 获取表 source-feature-table-names
        - label: DDL读取 source-feature-ddl
        
        
