name: default issue
description: default issue
body:
  - type: textarea
    id: basic-info
    attributes:
      label: "Comment"
      placeholder: "Leave a comment"
    validations:
      required: true
